/**
 * Seed trip for the in-memory application state.
 *
 * This module owns the canonical demo dataset.
 * App.tsx currently defines parallel constants; those will be retired
 * when App.tsx is migrated to consume this seed.
 */

import type { Trip } from "./trip";

export const INITIAL_TRIPS: Trip[] = [
  {
    id: "trip-1",
    name: "Cox's Bazar Getaway",
    destination: "Cox's Bazar",
    dates: "Aug 22–27, 2026",
    startDate: "2026-08-22",
    endDate: "2026-08-27",
    status: "active",
    budget: 60000,
    coverImage: undefined,
    travelerCount: 7,
    durationDays: 6,
    members: [
      { id: "1", name: "Farhan Ahmed",    initials: "FA", color: "#7C3AED", paid: 480,   balance: -5967, role: "member" },
      { id: "2", name: "Nadia Islam",     initials: "NI", color: "#0A86A0", paid: 19050, balance: 12603, role: "member" },
      { id: "3", name: "Rakib Hassan",    initials: "RH", color: "#059669", paid: 6000,  balance: -447,  role: "member" },
      { id: "4", name: "Tanha Khanam",    initials: "TK", color: "#D97706", paid: 2400,  balance: -4047, role: "member" },
      { id: "5", name: "Imran Chowdhury", initials: "IC", color: "#E11D48", paid: 0,     balance: -6447, role: "member" },
      { id: "6", name: "You",             initials: "RI", color: "#0A86A0", paid: 11400, balance: 4953,  isMe: true, role: "owner" },
      { id: "7", name: "Hasan Ahmed",     initials: "HA", color: "#64748B", paid: 0,     balance: -650,  role: "guest" },
    ],
    expenses: [
      {
        id: "1", title: "Hotel Seagull — 2 nights", amount: 14800, category: "lodging",
        paidBy: "2", splitIds: ["1","2","3","4","5","6"], date: "Aug 22", dateIso: "2026-08-22",
        addedBy: "2", addedAt: "Aug 22 at 2:15 PM",
      },
      {
        id: "2", title: "Hilsha fish dinner at Jhawban", amount: 4200, category: "food",
        paidBy: "6", splitIds: ["1","2","3","4","5","6"], date: "Aug 23", dateIso: "2026-08-23",
        addedBy: "6", addedAt: "Aug 23 at 8:45 PM",
        note: "Best hilsha in Cox's Bazar — we ordered the full fish.",
      },
      {
        id: "3", title: "CNG auto from station", amount: 480, category: "transport",
        paidBy: "1", splitIds: ["1","2","3","4","5","6"], date: "Aug 22", dateIso: "2026-08-22",
        addedBy: "1", addedAt: "Aug 22 at 11:20 AM",
      },
      {
        id: "4", title: "Beach chair & umbrella rentals", amount: 2400, category: "activity",
        paidBy: "4", splitIds: ["1","2","3","4","5","6"], date: "Aug 24", dateIso: "2026-08-24",
        addedBy: "4", addedAt: "Aug 24 at 10:00 AM",
      },
      {
        id: "5", title: "Breakfast buffet × 6", amount: 3600, category: "food",
        paidBy: "2", splitIds: ["1","2","3","4","5","6"], date: "Aug 24", dateIso: "2026-08-24",
        addedBy: "6", addedAt: "Aug 24 at 9:30 AM",
      },
      {
        id: "6", title: "Speed boat to Saint Martin", amount: 6000, category: "transport",
        paidBy: "3", splitIds: ["1","2","3","4","5","6"], date: "Aug 25", dateIso: "2026-08-25",
        addedBy: "3", addedAt: "Aug 25 at 7:00 AM",
        syncStatus: "pending",
      },
      {
        id: "7", title: "Mermaid Beach Resort — 1 night", amount: 7200, category: "lodging",
        paidBy: "6", splitIds: ["1","2","3","4","5","6"], date: "Aug 25", dateIso: "2026-08-25",
        addedBy: "6", addedAt: "Aug 25 at 6:45 PM",
      },
      {
        id: "8", title: "Hasan's taxi to resort", amount: 650, category: "transport",
        paidBy: "2", splitIds: ["7"], date: "Aug 22", dateIso: "2026-08-22",
        addedBy: "6", addedAt: "Aug 22 at 3:00 PM",
      },
    ],
    settlements: [
      { id: "s1", from: "5", to: "2", amount: 6447, date: "Aug 26", dateIso: "2026-08-26", recordedBy: "6" },
      { id: "s2", from: "1", to: "2", amount: 5967, date: "Aug 26", dateIso: "2026-08-26", recordedBy: "1" },
    ],
  },
  {
    id: "trip-2",
    name: "Sajek Valley Expedition",
    destination: "Sajek Valley",
    dates: "Oct 18–22, 2026",
    startDate: "2026-10-18",
    endDate: "2026-10-22",
    status: "active",
    budget: 50000,
    coverImage: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80",
    travelerCount: 5,
    durationDays: 5,
    members: [
      { id: "m1", name: "Rafi (You)",    initials: "R", color: "#0A86A0", paid: 2450, balance: 0, isMe: true, role: "owner" },
      { id: "m2", name: "Shanto",        initials: "S", color: "#10B981", paid: 0,    balance: 0, role: "member" },
      { id: "m3", name: "Jamil",         initials: "J", color: "#EC4899", paid: 6200, balance: 0, role: "member" },
      { id: "m4", name: "Shad",          initials: "S", color: "#F59E0B", paid: 0,    balance: 0, role: "member" },
      { id: "m5", name: "Rabbi",         initials: "R", color: "#8B5CF6", paid: 8500, balance: 0, role: "member" },
    ],
    expenses: [
      {
        id: "exp-1",
        title: "Sajek Resort Booking",
        amount: 6200,
        category: "lodging",
        paidBy: "m3",
        splitIds: ["m1", "m2", "m3", "m4", "m5"],
        date: "Oct 20",
        dateIso: "2026-10-20",
        addedBy: "m3",
        addedAt: "Oct 20, 2:00 PM",
      },
      {
        id: "exp-2",
        title: "Dinner at Stone Cafe",
        amount: 2450,
        category: "food",
        paidBy: "m1",
        splitIds: ["m1", "m2", "m3", "m4", "m5"],
        date: "Oct 19",
        dateIso: "2026-10-19",
        addedBy: "m1",
        addedAt: "Oct 19, 8:30 PM",
      },
      {
        id: "exp-3",
        title: "Jeep (Chander Gari) Rent",
        amount: 8500,
        category: "transport",
        paidBy: "m5",
        splitIds: ["m1", "m2", "m3", "m4", "m5"],
        date: "Oct 19",
        dateIso: "2026-10-19",
        addedBy: "m5",
        addedAt: "Oct 19, 10:00 AM",
      },
      {
        id: "exp-4",
        title: "Konglak Para Tea & Snacks",
        amount: 850,
        category: "food",
        paidBy: "m4",
        splitIds: ["m1", "m2", "m3", "m4", "m5"],
        date: "Oct 19",
        dateIso: "2026-10-19",
        addedBy: "m4",
        addedAt: "Oct 19, 4:30 PM",
      },
    ],
    settlements: [],
  },
  {
    id: "trip-3",
    name: "Sylhet Weekend",
    destination: "Sylhet",
    dates: "Jun 14–16, 2026",
    startDate: "2026-06-14",
    endDate: "2026-06-16",
    status: "completed",
    budget: 30000,
    coverImage: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80",
    travelerCount: 5,
    durationDays: 3,
    members: [
      { id: "sy1", name: "Rafi (You)", initials: "R", color: "#0A86A0", paid: 12000, balance: 0, isMe: true, role: "owner" },
      { id: "sy2", name: "Tanvir",     initials: "T", color: "#2563EB", paid: 6800,  balance: 0, role: "member" },
      { id: "sy3", name: "Nayeem",     initials: "N", color: "#059669", paid: 6000,  balance: 0, role: "member" },
      { id: "sy4", name: "Fahim",      initials: "F", color: "#D97706", paid: 0,     balance: 0, role: "member" },
      { id: "sy5", name: "Shakil",     initials: "S", color: "#7C3AED", paid: 0,     balance: 0, role: "member" },
    ],
    expenses: [
      {
        id: "sy-1",
        title: "Grand Sultan Resort",
        amount: 15400,
        category: "lodging",
        paidBy: "sy1",
        splitIds: ["sy1", "sy2", "sy3", "sy4", "sy5"],
        date: "Jun 15",
        dateIso: "2026-06-15",
        addedBy: "sy1",
        addedAt: "Jun 15, 12:00 PM",
      },
      {
        id: "sy-2",
        title: "Tea Garden Tour",
        amount: 3200,
        category: "activity",
        paidBy: "sy2",
        splitIds: ["sy1", "sy2", "sy3", "sy4", "sy5"],
        date: "Jun 15",
        dateIso: "2026-06-15",
        addedBy: "sy2",
        addedAt: "Jun 15, 10:00 AM",
      },
      {
        id: "sy-3",
        title: "Local Lunch at Shahi Dine",
        amount: 1800,
        category: "food",
        paidBy: "sy3",
        splitIds: ["sy1", "sy2", "sy3", "sy4", "sy5"],
        date: "Jun 16",
        dateIso: "2026-06-16",
        addedBy: "sy3",
        addedAt: "Jun 16, 1:00 PM",
      },
      {
        id: "sy-4",
        title: "Rent Car for Jaflong",
        amount: 7500,
        category: "transport",
        paidBy: "sy1",
        splitIds: ["sy1", "sy2", "sy3", "sy4", "sy5"],
        date: "Jun 16",
        dateIso: "2026-06-16",
        addedBy: "sy1",
        addedAt: "Jun 16, 8:00 AM",
      },
    ],
    settlements: [
      { id: "sy-s1", from: "sy4", to: "sy1", amount: 1500, date: "Jun 17", dateIso: "2026-06-17", recordedBy: "sy1" },
    ],
  },
];
